name: Full K8s CI/CD (Terraform + kubeadm)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 🔹 AWS Login
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 🔹 Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

    # 🔹 Get IPs
    - name: Get Outputs
      id: tfout
      run: |
        echo "MASTER_IP=$(terraform output -raw master_ip)" >> $GITHUB_ENV
        echo "WORKER_IPS=$(terraform output -json worker_ips | jq -r '.[]')" >> $GITHUB_ENV
      working-directory: terraform

    # 🔹 Create PEM
    - name: Create Key
      run: |
        echo "${{ secrets.EC2_KEY_PAIR }}" > key.pem
        chmod 400 key.pem

    # 🔹 Setup Master
    - name: Setup Master Node
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no scripts/master.sh ubuntu@$MASTER_IP:/home/ubuntu/
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "chmod +x master.sh && ./master.sh"

    # 🔹 Get Join Command
    - name: Fetch Join Script
      run: |
        scp -i key.pem ubuntu@$MASTER_IP:/home/ubuntu/join.sh ./join.sh

    # 🔹 Setup Workers
    - name: Setup Worker Nodes
      run: |
        for ip in $WORKER_IPS; do
          scp -i key.pem -o StrictHostKeyChecking=no scripts/worker.sh ubuntu@$ip:/home/ubuntu/
          scp -i key.pem -o StrictHostKeyChecking=no join.sh ubuntu@$ip:/home/ubuntu/
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$ip "chmod +x worker.sh && ./worker.sh"
        done